sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - parallel

install:
  - pip install futures
  - pip install http://ftp.openquake.org/python-wheels/numpy-1.8.2-cp27-none-linux_x86_64.whl
  - pip install http://ftp.openquake.org/python-wheels/scipy-0.16.0-cp27-none-linux_x86_64.whl
  - pip install http://ftp.openquake.org/python-wheels/Cython-0.22.1-cp27-none-linux_x86_64.whl
  - pip install http://ftp.openquake.org/python-wheels/Shapely-1.5.9-py2-none-any.whl
  - pip install http://ftp.openquake.org/python-wheels/h5py-2.2.1-cp27-none-linux_x86_64.whl
  - pip install https://github.com/gem/oq-hazardlib/archive/master.zip
  - python setup.py install

script:
  - PYTHONPATH=. nosetests -vsx -a'!slow' --with-xunit --nologcapture --with-doctest
  - # cd bin; python slowtests ../nosetests.xml
